### ISSUE TITLE
Organize coding style

### ISSUE THREAD

**Issue by peter279k** [orbisius/orbisius-dot-env#2]
After looking at the `orbisius_dot_env.php` file, it doesn't know about the coding style on this repository.

Can repository owner describe this :-)?

**Comment by lordspace** [comment]
Nope. Too busy.

**Comment by peter279k** [comment]
If possible, I can define [PSR-12 coding style ](https://www.php-fig.org/psr/psr-12/)via `PHP_CodeSniffer`.

And create related PR to complete this work I mention....

Once repository owner is accepted, I would be happy to do this.
